spring:  
  datasource: 
    schema: classpath*:schema.sql
    data: classpath*:data.sql
    hikari: 
      driverClassName: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/dev
      username: root
      password: skcc
    initialization-mode: always

      

logging: 
  file: 
    max-size: 10MB
    max-history: 7
    name: logs/${spring.application.name}.log
   

    

  

