spring:  
  application:
    name: sample-api-service
  datasource:  
    hikari:  
      driverClassName: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/prod
      username: root
      password: skcc
    initialization-mode: always
      
logging:   
  file:  
    max-history: 7
    max-size: 10MB
    name: logs/${spring.application.name}.log

